Update content for the contact us page
canon193/your-tech-partner pull request #8
Opened 2023-09-22 15:06 UTC by kuem2405

2023-09-24 17:00 UTC, canon193 commented
@kuem2405 
Pls confirm the build with: npm run build
There is some issue with empty params of <ProjectCard>

2023-09-24 17:00 UTC, canon193 requested changes

2023-09-25 14:08 UTC, canon193 commented
@kuem2405 
npm run build failed.
- info Loaded env from E:\OneDrive\OneDrive - kasumii\YourTechPartner\.env
- info Linting and checking validity of types ..Failed to compile.

./pages/contact.tsx:10:19
Type error: Cannot find module 'axios' or its corresponding type declarations.

   8 | import { FiMail, FiPhoneCall, FiSlack } from 'react-icons/fi'
   9 | import {LiaSkype} from 'react-icons/lia'
> 10 | import axios from "axios";
     |                   ^
  11 |
  12 | const Contact = () => {
  13 |   const [state, setState] = React.useState({

2023-09-26 13:55 UTC, kuem2405 commented
> @kuem2405 Pls confirm the build with: npm run build There is some issue with empty params of

This has been fixed

2023-09-26 16:22 UTC, canon193 approved these changes

2023-09-26 16:22 UTC, merged